rootProject.name = 'distributed-key-value-store-raft'

include 'kv-common'
include 'kv-storage-api'
include 'kv-storage-rocksdb'
include 'kv-storage-toy-lsm'
include 'kv-raft-core'
include 'kv-raft-kv'
include 'kv-partitioning-range'
include 'kv-multi-raft'
include 'kv-leader-lease'
include 'kv-mvcc'
include 'kv-membership'
include 'kv-node'
include 'kv-client'
include 'kv-bench'
include 'kv-simulator'
include 'kv-admin'
